export class GameState {
  id: number;
  playerName: string;
  gasLevel: number;
  ventAmount: number;
  seconds: number;
  resources: number;
  filterCost: number;
  filtersOwned: number;
  autoOwned: number;
  autoCost: number;
  increasedBy: number;
  secondGame: boolean;
  thirdGame: boolean;
  fourthGame: boolean;
  clonesAvailable: number;
  foodAvailable: number;
  farmers: number;
  gatherers: number;
  builders: number;
  scouts: number;
  conquerers: number;
  cloneUpgrade: number;
  cloneUpgradeCost: number;
  gatherersOn: boolean;
  buildersOn: boolean;
  scoutsOn: boolean;
  conquerersOn: boolean;
}
